import { resolve } from 'path';
import { defineConfig } from 'vite';

/**
 * syrinx builds straight into the blog's static tree, the same way apeiron does.
 * The image never runs npm (the Dockerfile only copies `aethera/`), so the built
 * bundle is a committed artifact — rebuild and commit it when src/ changes.
 *
 * `npm run dev` still serves the standalone `index.html`, because the headless
 * checks in scripts/ drive a real browser against it. Port is pinned here rather
 * than passed on the command line so those scripts don't depend on remembering
 * a flag.
 */
export default defineConfig({
  server: { port: 5199, strictPort: true },
  preview: { port: 5199, strictPort: true },
  build: {
    outDir: resolve(__dirname, '../aethera/static/syrinx'),
    emptyOutDir: false,
    rollupOptions: {
      input: resolve(__dirname, 'src/main.ts'),
      output: {
        entryFileNames: 'syrinx.js',
        assetFileNames: 'syrinx.[ext]',
        format: 'iife',
      },
    },
    /**
     * Without this, an iife build with a bare JS entry inlines the stylesheet
     * into a JS-injected <style> tag. That would mean no syrinx.css to <link>
     * (base.html can't get styles any other way — htmx boost never swaps <head>)
     * and the wake overlay would sit unstyled until ~150kB gzip had parsed.
     */
    cssCodeSplit: false,
    // three is ~590kB on its own; the warning is noise, not news
    chunkSizeWarningLimit: 900,
    /**
     * Off deliberately: the map is ~3MB and is regenerated byte-differently on
     * every build, so committing it churns the repo for little — src/ is right
     * there in the same tree. `npm run dev` still has full maps.
     */
    sourcemap: false,
  },
});
