/**
 * census.ts — who lives here.
 *
 * The simulation periodically identifies the famous citizens living in the
 * viewport (spaceships, oscillators, and the common still-life ash) so the
 * ticker can greet them by name. Recognition works by matching each small
 * isolated cluster against dihedral-canonical signatures of every phase of
 * every known pattern — signatures are generated by actually simulating the
 * patterns, so the library below stays honest.
 *
 * life.py leans on scipy.ndimage for this (binary_dilation, label,
 * find_objects). Those are small enough to write out, which also means the
 * census works everywhere here; in the terminal it needed scipy.
 */

import { PATTERNS, type Cells } from './constants';

/** name → [cells, period]. Spaceships/oscillators cover all their phases. */
const CENSUS_SEEDS: Readonly<Record<string, readonly [Cells, number]>> = {
  block: [[[0, 0], [0, 1], [1, 0], [1, 1]], 1],
  beehive: [[[0, 1], [0, 2], [1, 0], [1, 3], [2, 1], [2, 2]], 1],
  loaf: [[[0, 1], [0, 2], [1, 0], [1, 3], [2, 1], [2, 3], [3, 2]], 1],
  boat: [[[0, 0], [0, 1], [1, 0], [1, 2], [2, 1]], 1],
  tub: [[[0, 1], [1, 0], [1, 2], [2, 1]], 1],
  ship: [[[0, 0], [0, 1], [1, 0], [1, 2], [2, 1], [2, 2]], 1],
  pond: [[[0, 1], [0, 2], [1, 0], [1, 3], [2, 0], [2, 3], [3, 1], [3, 2]], 1],
  blinker: [[[0, 0], [0, 1], [0, 2]], 2],
  toad: [[[0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2]], 2],
  beacon: [[[0, 0], [0, 1], [1, 0], [2, 3], [3, 2], [3, 3]], 2],
  glider: [PATTERNS.glider ?? [], 4],
  lwss: [PATTERNS.lwss ?? [], 4],
  hwss: [PATTERNS.hwss ?? [], 4],
  pulsar: [PATTERNS.pulsar ?? [], 3],
  pentadecathlon: [PATTERNS.pentadecathlon ?? [], 15],
};

/** Larger clusters than this can't be any known pattern — skip early */
export const CENSUS_MAX_CELLS = 60;
export const CENSUS_MAX_DIM = 20;

/** A cropped bitmap: h rows × w cols, row-major, 0/1. */
interface Bitmap {
  h: number;
  w: number;
  bits: Uint8Array;
}

/**
 * Canonical signature over the 8 dihedral transforms of a cropped bitmap.
 * life.py compares packbits byte strings; any canonical choice works as long
 * as the library and the lookup share it, and this one is a plain string.
 */
function canonicalSignature(m: Bitmap): string {
  let best: string | null = null;
  for (let t = 0; t < 8; t++) {
    const swap = t >= 4; // transpose first
    const h = swap ? m.w : m.h;
    const w = swap ? m.h : m.w;
    let s = `${h}x${w}:`;
    for (let r = 0; r < h; r++) {
      for (let c = 0; c < w; c++) {
        let rr = t & 1 ? h - 1 - r : r;
        let cc = t & 2 ? w - 1 - c : c;
        if (swap) [rr, cc] = [cc, rr];
        s += m.bits[rr * m.w + cc] ? '1' : '0';
      }
    }
    if (best === null || s < best) best = s;
  }
  return best ?? '';
}

let signatures: Map<string, string> | null = null;

/**
 * Build (once) the signature → name table by simulating each seed pattern
 * through all phases of its period on a quiet private grid.
 */
export function censusSignatures(): Map<string, string> {
  if (signatures) return signatures;
  const sigs = new Map<string, string>();
  for (const [name, [cells, period]] of Object.entries(CENSUS_SEEDS)) {
    const h = Math.max(...cells.map(([r]) => r)) + 1;
    const w = Math.max(...cells.map(([, c]) => c)) + 1;
    // Room to breathe: patterns may grow/travel a little mid-phase
    const size = Math.max(h, w) + 2 * (period + 4);
    let grid = new Uint8Array(size * size);
    const oy = Math.floor((size - h) / 2);
    const ox = Math.floor((size - w) / 2);
    for (const [r, c] of cells) grid[(oy + r) * size + ox + c] = 1;

    for (let p = 0; p < period; p++) {
      const crop = cropToBbox(grid, size, size);
      if (crop) {
        const sig = canonicalSignature(crop);
        if (!sigs.has(sig)) sigs.set(sig, name);
      }
      // One Life step (wrapping, as np.roll does; the grid is roomy enough)
      const next = new Uint8Array(size * size);
      for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
          let n = 0;
          for (let dy = -1; dy <= 1; dy++) {
            for (let dx = -1; dx <= 1; dx++) {
              if (dy || dx) n += grid[((y + dy + size) % size) * size + ((x + dx + size) % size)] ?? 0;
            }
          }
          const alive = grid[y * size + x] === 1;
          next[y * size + x] = (alive && (n === 2 || n === 3)) || (!alive && n === 3) ? 1 : 0;
        }
      }
      grid = next;
    }
  }
  signatures = sigs;
  return sigs;
}

function cropToBbox(mask: Uint8Array, h: number, w: number): Bitmap | null {
  let y0 = h;
  let y1 = -1;
  let x0 = w;
  let x1 = -1;
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (!mask[y * w + x]) continue;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
    }
  }
  if (y1 < 0) return null;
  const ch = y1 - y0 + 1;
  const cw = x1 - x0 + 1;
  const bits = new Uint8Array(ch * cw);
  for (let y = 0; y < ch; y++) {
    for (let x = 0; x < cw; x++) bits[y * cw + x] = mask[(y0 + y) * w + x0 + x] ?? 0;
  }
  return { h: ch, w: cw, bits };
}

export interface CensusResult {
  counts: Map<string, number>;
  /** (name, row, col) in viewport coordinates, at most 48 */
  sites: [string, number, number][];
}

/**
 * Count known patterns in a viewport-sized occupancy map (h × w, row-major).
 *
 * Small gaps are bridged with dilation before labeling so patterns with
 * 8-disconnected parts (the pulsar) group as one cluster; each cluster is
 * then matched against the canonical signature table. Returns null when the
 * scene is too busy to be worth it (more than 400 clusters), as life.py does.
 */
export function census(occupied: Uint8Array, h: number, w: number): CensusResult | null {
  const sigs = censusSignatures();

  // binary_dilation(iterations=2) with scipy's default cross: a Manhattan
  // radius-2 diamond around every occupied cell, clipped at the border.
  const merged = new Uint8Array(h * w);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (!occupied[y * w + x]) continue;
      for (let dy = -2; dy <= 2; dy++) {
        const yy = y + dy;
        if (yy < 0 || yy >= h) continue;
        const span = 2 - Math.abs(dy);
        const xa = Math.max(0, x - span);
        const xb = Math.min(w - 1, x + span);
        merged.fill(1, yy * w + xa, yy * w + xb + 1);
      }
    }
  }

  // label with 8-connectivity, raster order (scipy numbers labels the same way)
  const labels = new Int32Array(h * w);
  const boxes: { y0: number; y1: number; x0: number; x1: number }[] = [];
  const stack: number[] = [];
  for (let start = 0; start < h * w; start++) {
    if (!merged[start] || labels[start]) continue;
    const id = boxes.length + 1;
    if (id > 400) return null;
    const box = { y0: h, y1: -1, x0: w, x1: -1 };
    labels[start] = id;
    stack.push(start);
    while (stack.length) {
      const i = stack.pop() ?? 0;
      const y = Math.floor(i / w);
      const x = i - y * w;
      if (y < box.y0) box.y0 = y;
      if (y > box.y1) box.y1 = y;
      if (x < box.x0) box.x0 = x;
      if (x > box.x1) box.x1 = x;
      for (let dy = -1; dy <= 1; dy++) {
        const yy = y + dy;
        if (yy < 0 || yy >= h) continue;
        for (let dx = -1; dx <= 1; dx++) {
          const xx = x + dx;
          if (xx < 0 || xx >= w) continue;
          const j = yy * w + xx;
          if (merged[j] && !labels[j]) {
            labels[j] = id;
            stack.push(j);
          }
        }
      }
    }
    boxes.push(box);
  }
  if (boxes.length === 0) return null;

  const counts = new Map<string, number>();
  const sites: [string, number, number][] = [];
  boxes.forEach((box, k) => {
    const id = k + 1;
    const bh = box.y1 - box.y0 + 1;
    const bw = box.x1 - box.x0 + 1;
    // Dilated bbox is at most 4 wider than the pattern itself
    if (bh > CENSUS_MAX_DIM + 4 || bw > CENSUS_MAX_DIM + 4) return;
    const cluster = new Uint8Array(bh * bw);
    let n = 0;
    let sy = 0;
    let sx = 0;
    for (let y = 0; y < bh; y++) {
      for (let x = 0; x < bw; x++) {
        const i = (box.y0 + y) * w + box.x0 + x;
        if (occupied[i] && labels[i] === id) {
          cluster[y * bw + x] = 1;
          n++;
          sy += y;
          sx += x;
        }
      }
    }
    if (n < 3 || n > CENSUS_MAX_CELLS) return;
    const crop = cropToBbox(cluster, bh, bw);
    const name = crop ? sigs.get(canonicalSignature(crop)) : undefined;
    if (name === undefined) return;
    counts.set(name, (counts.get(name) ?? 0) + 1);
    if (sites.length < 48) sites.push([name, box.y0 + Math.floor(sy / n), box.x0 + Math.floor(sx / n)]);
  });
  return { counts, sites };
}
