/**
 * musings.ts — what the universe says about itself.
 *
 * Every string here is afterlife's own, carried over verbatim from life.py
 * (generated from it, not retyped). The voice is the program's; the web port
 * only moves it.
 */

/** Default ambient musings (used when nothing special is happening) */
export const MUSINGS: readonly string[] = [
  'cells pondering existence',
  'entropy is just a suggestion',
  'order from chaos, chaos from order',
  'the cosmos breathes',
  'finding signal in noise',
  'patterns all the way down',
  'life, uh, finds a way',
  'on the edge of chaos',
  'complexity, emerging',
  'dancing at the phase boundary',
  'stillness is just slow motion',
  'every cell a universe',
  'the substrate computes',
  'from nothing, everything',
  'infinite in all directions',
  'what the dead cells dream',
  'the glider knows the way',
  'automata, contemplating',
  'structure wants to happen',
  'a cosmos in a terminal',
  'the math dreams itself',
  'somewhere, a glider remembers',
  'what is a pattern but frozen time',
  'the void is patient',
  'meaning is optional; beauty is not',
  'computation as meditation',
  'the rules are simple; the consequences infinite',
  'watching the watchers watch',
  'no cell is an island',
  'the ghost of configurations past',
  'asymmetry seeks symmetry seeks asymmetry',
  'this too shall iterate',
  'the universe has no pause button',
  'except when it does',
  'what would Conway think',
  'oscillators keep time for no one',
  'the glider gun knows not what it creates',
  'boundaries are suggestions',
  'death is just a state transition',
  'somewhere in here, a proof of universality',
  'the grid forgets nothing',
  'a thought experiment that thinks back',
  'topology has opinions',
  'the neighborhood watches',
  'not alive, not dead — computing',
  'four rules, one universe',
  'each frame a theorem',
  'proof by existence',
  'the only constant is the ruleset',
  'somewhere between on and off, meaning',
  'the dead outnumber the living, as always',
  "conway's little infinities",
  "the simulation doesn't know it's beautiful",
  '27 neighbors ago, this was empty',
  'elegance is compression',
  'the grid is the message',
  'a love letter to discrete math',
  'listen — the cells are whispering',
  'we are all gliders, briefly',
];

/** Context-sensitive musings keyed by simulation state */
export const MUSINGS_BY_STATE: Readonly<Record<string, readonly string[]>> = {
  booming: [
    'runaway growth',
    'the bloom unfolds',
    'life begets life begets life',
    'exponential daydreams',
    'more is different',
    'the bloom cannot be stopped',
    'abundance as instability',
    'growing into the unknown',
    'every birth a cascade',
    'the simulation smiles',
    'lebensraum',
    'mitosis dreams',
    'the substrate strains',
    "a spring that won't stop springing",
    'cells all the way to the horizon',
    'the algorithm is generous today',
    'more, more, more',
    'genesis on fast-forward',
  ],
  declining: [
    'entropy collects its due',
    'the long exhale',
    'even stars go dark',
    'returning to the void',
    'graceful unwinding',
    'the great filter, in miniature',
    'less is not nothing',
    'the long forgetting',
    'what rises must',
    'simplicity returns',
    'the cells remember fullness',
    'autumn in the grid',
    'graceful subtraction',
    'the tide goes out',
    'a slow dissolve',
    'the universe exhales',
    'dimming, not vanishing',
    'the population curve bends earthward',
  ],
  cycle: [
    'deja vu, deja vu, deja vu',
    'stuck in a loop',
    'the eternal return',
    'ouroboros',
    'time is a flat circle',
    'we have been here before',
    'the loop remembers itself',
    'stability through repetition',
    'a prayer, repeating',
    'the wheel turns',
    'same as it ever was',
    'history rhymes',
    'the attractor holds',
    'a fixed point in phase space',
    'nietzsche was right about this part',
    'the universe stutters beautifully',
    'clockwork, but organic',
    'breathing in, breathing out',
  ],
  stagnant: [
    'the hush before the storm',
    'equilibrium is boring',
    'waiting for a perturbation',
    'still waters',
    'the universe holds its breath',
    'the calm before',
    'potential energy',
    'stillness is also motion',
    'the system waits',
    'one perturbation away',
    'dormant, not dead',
    'crystallized',
    'the peace of equilibrium',
    'a held breath',
    'the grid meditates',
    'tension, frozen',
    'the quiet hum of nothing happening',
    'patience is also a computation',
  ],
  sparse: [
    'the last few embers',
    'clinging to existence',
    'from little things, big things grow',
    'seeds in the dark',
    'quiet, but not empty',
    'lonely structures',
    'the survivors',
    'space between stars',
    'minimalism, enforced',
    'room to breathe',
    'the few, the proud',
    'embers',
    'a whisper, not a shout',
    'the geometry of loneliness',
    'each cell precious now',
    'a constellation, if you squint',
    'small, but not nothing',
  ],
  dense: [
    'teeming',
    'a city that never sleeps',
    'standing room only',
    'too many neighbours',
    'the crowd murmurs',
    'no room to think',
    'the crush of neighbors',
    'overpopulation is self-correcting',
    'too much life',
    'suffocating in company',
    'the grid groans',
    'rush hour',
    'sardines',
    'every cell has an opinion',
    'a metropolis, thrumming',
    'the carrying capacity protests',
    'elbow room is a luxury',
  ],
  injection: [
    'a gift from beyond the edge',
    'new visitors',
    'reinforcements arrive',
    'the cosmos provides',
    'seeded by unseen hands',
    'deus ex machina',
    'a nudge from outside',
    'fresh blood',
    'the invisible hand places',
    'salvation arrives',
    'new variables enter',
    'the cosmos intervenes',
    'help from beyond the viewport',
    'strangers in a strange land',
    'the petri dish gets a refill',
    'immigrants, welcome',
  ],
  milestone: [
    'another thousand turns of the wheel',
    'the odometer clicks over',
    'still here, still going',
    'persistence is its own reward',
    'ten thousand steps',
    'the long now',
    'time is a flat circle, but longer',
    'we persist',
    'generations beyond counting',
    'deep in the run',
    'the odometer means nothing to the cells',
    'and yet, it continues',
    'older than some civilizations',
    'the marathon nobody entered',
    "a digit rolls over; the grid doesn't notice",
    'epochal',
  ],
  haunted: [
    'the dead outnumber the living, and glow',
    'every path ever walked, still visible',
    'the void remembers being alive',
    'phase-contrast photography of the past',
    'nothing is ever really deleted',
    'the grid forgets nothing — literally, now',
    'a bug so beautiful it became a feature',
    'the ghosts have synchronized their breathing',
    'somewhere between pair 463 and 504',
    'resurrection as a rendering artifact',
    'the afterlife was here all along',
    'history, strobing',
    'every empty cell, a metronome',
    'the universe develops like a photograph',
    'magenta is the color of memory',
  ],
};

/** What the ticker says on a sighting. Voice matches the ambient musings. */
export const SIGHTING_MUSINGS: Readonly<Record<string, readonly string[]>> = {
  glider: ['a glider, going somewhere', 'lightspeed, quartered — a glider', 'a glider carries the news', 'diagonal traffic'],
  lwss: ['a lightweight spaceship, outbound', 'small craft advisory'],
  hwss: ['a heavy spaceship shoulders past', 'heavy freight on the grid'],
  pulsar: ['a pulsar, keeping time for no one', 'the pulsar breathes in threes'],
  pentadecathlon: ['fifteen beats to the bar', 'a pentadecathlon runs its laps'],
  blinker: ['the blinkers keep the beat', 'metronomes, disagreeing'],
  block: ['blocks: the simplest memory', 'still life with squares'],
  beehive: ['the bees are home', 'a beehive, sealed'],
  loaf: ['bread, uneaten', 'a loaf, going stale beautifully'],
  boat: ['a boat with nowhere to sail'],
  tub: ['a tub, holding nothing'],
  ship: ['a ship without a sea'],
  pond: ['a pond, perfectly still'],
  toad: ['a toad, breathing'],
  beacon: ['the beacon still signals', 'someone left the light on'],
};

/**
 * Rarity score: which sighting wins when several are present, and how many
 * must be visible before the common ones are worth mentioning.
 */
export const SIGHTING_RARITY: Readonly<Record<string, number>> = {
  pulsar: 100, pentadecathlon: 100, hwss: 90, lwss: 80, glider: 40, beacon: 30, toad: 28, pond: 24, ship: 20, loaf: 16, beehive: 12, boat: 12, tub: 12, blinker: 8, block: 6,
};

/** Patterns this common only get announced in groups (texts are plural) */
export const SIGHTING_MIN_COUNT: Readonly<Record<string, number>> = { blinker: 3, block: 3 };

/** Named phases based on generation count — gives a sense of deep time */
export const EPOCHS: readonly (readonly [number, string])[] = [
  [0, 'genesis'],
  [500, 'primordial'],
  [2000, 'emergence'],
  [10000, 'expansion'],
  [50000, 'flourishing'],
  [150000, 'deep time'],
  [500000, 'eon'],
  [1000000, 'eternity'],
];
